name: release

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          make
          mkdir idle-forever-linux-amd64
          mv idle-forever idle-forever-linux-amd64
          tar czf idle-forever-linux-amd64.tar.gz idle-forever-linux-amd64
      - uses: actions/upload-artifact@v6
        with:
          name: idle-forever-linux-amd64
          path: idle-forever-linux-amd64.tar.gz
  linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - run: |
          make
          mkdir idle-forever-linux-arm64
          mv idle-forever idle-forever-linux-arm64
          tar czf idle-forever-linux-arm64.tar.gz idle-forever-linux-arm64
      - uses: actions/upload-artifact@v6
        with:
          name: idle-forever-linux-arm64
          path: idle-forever-linux-arm64.tar.gz
  release:
    runs-on: ubuntu-latest
    needs:
      - linux-amd64
      - linux-arm64
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: idle-forever-linux-amd64
      - uses: actions/download-artifact@v7
        with:
          name: idle-forever-linux-arm64
      - name: create release and upload release assets
        run: |
          find . -ls
          gh release create --repo ${{ github.repository }} ${{ github.ref }} idle-forever-linux-amd64/idle-forever-linux-amd64.tar.gz idle-forever-linux-arm64/idle-forever-linux-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
