name: release

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          make
          mkdir linux-amd64
          mv idle-forever linux-amd64
          tar czf linux-amd64.tar.gz linux-amd64
      - uses: actions/upload-artifact@v6
        with:
          name: linux-amd64.tar.gz
          path: linux-amd64.tar.gz
  linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - run: |
          make
          mkdir linux-arm64
          mv idle-forever linux-arm64
          tar czf linux-arm64.tar.gz linux-arm64
      - uses: actions/upload-artifact@v6
        with:
          name: linux-arm64.tar.gz
          path: linux-arm64.tar.gz
  release:
    runs-on: ubuntu-latest
    needs:
      - linux-amd64
      - linux-arm64
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: linux-amd64.tar.gz
          path: linux-amd64.tar.gz
      - uses: actions/download-artifact@v7
        with:
          name: linux-arm64.tar.gz
          path: linux-arm64.tar.gz
      - name: create release and upload release assets
        run: gh release create --repo ${{ github.repository }} ${{ github.ref }} linux-amd64.tar.gz linux-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
